version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: estoque_postgres
    environment:
      POSTGRES_DB: estoque_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
